"""empty message

Revision ID: 00408ec985fc
Revises: f41f6f22c982
Create Date: 2021-08-05 15:23:21.586667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00408ec985fc'
down_revision = 'f41f6f22c982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot', sa.Column('submitter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'spot', 'user', ['submitter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spot', type_='foreignkey')
    op.drop_column('spot', 'submitter_id')
    # ### end Alembic commands ###
