"""Add is_deleted field to spots

Revision ID: 004888b112c6
Revises: ea6e76cc3f95
Create Date: 2022-01-19 18:00:26.961106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004888b112c6'
down_revision = 'ea6e76cc3f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot', sa.Column('is_deleted', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot', 'is_deleted')
    # ### end Alembic commands ###
