"""empty message

Revision ID: 00c0ff6fd3f2
Revises: 7cfc8cd422a4
Create Date: 2021-08-07 12:57:17.598972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c0ff6fd3f2'
down_revision = '7cfc8cd422a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('spot', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot', 'longitude')
    op.drop_column('spot', 'latitude')
    # ### end Alembic commands ###
