"""Make locality name non-nullable

Revision ID: 02406a792cf4
Revises: fa8290e9dddd
Create Date: 2021-09-10 14:24:04.327997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02406a792cf4'
down_revision = 'fa8290e9dddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locality', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locality', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
