"""add title field for reviews

Revision ID: 085900189cdb
Revises: 004888b112c6
Create Date: 2022-04-16 13:14:52.783903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085900189cdb'
down_revision = '004888b112c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'title')
    # ### end Alembic commands ###
