"""empty message

Revision ID: 0b40974880fd
Revises: 61a2e82aa4f3
Create Date: 2021-07-26 18:05:59.352748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b40974880fd'
down_revision = '61a2e82aa4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot', 'max_depth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot', sa.Column('max_depth', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
