"""add to diveshop model

Revision ID: 117a5853246d
Revises: f69f31bbf7d2
Create Date: 2022-07-20 16:59:20.522675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117a5853246d'
down_revision = 'f69f31bbf7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dive_shop', sa.Column('padi_store_id', sa.String(), nullable=True))
    op.add_column('dive_shop', sa.Column('description', sa.String(), nullable=True))
    op.add_column('dive_shop', sa.Column('hours', sa.JSON(), nullable=True))
    op.add_column('dive_shop', sa.Column('country_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dive_shop', 'country_name')
    op.drop_column('dive_shop', 'hours')
    op.drop_column('dive_shop', 'description')
    op.drop_column('dive_shop', 'padi_store_id')
    # ### end Alembic commands ###
