"""Add shortname for tag urls

Revision ID: 20e53de3f32e
Revises: efd6bfcbe174
Create Date: 2022-01-17 12:21:51.367904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e53de3f32e'
down_revision = 'efd6bfcbe174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('short_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tag', ['short_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_column('tag', 'short_name')
    # ### end Alembic commands ###
