"""add extra review fields

Revision ID: 27b65909b8ae
Revises: 085900189cdb
Create Date: 2022-04-17 15:31:41.847751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b65909b8ae'
down_revision = '085900189cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('dive_length', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('entry', sa.String(), nullable=True))
    op.add_column('review', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('start_air', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('end_air', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('air_type', sa.String(), nullable=True))
    op.add_column('review', sa.Column('air_temp', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('water_temp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'water_temp')
    op.drop_column('review', 'air_temp')
    op.drop_column('review', 'air_type')
    op.drop_column('review', 'end_air')
    op.drop_column('review', 'start_air')
    op.drop_column('review', 'weight')
    op.drop_column('review', 'entry')
    op.drop_column('review', 'dive_length')
    # ### end Alembic commands ###
