"""Add JSON for padi data dump

Revision ID: 2a8fb0a6f2fe
Revises: e42cfe747172
Create Date: 2025-04-06 15:35:11.451073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8fb0a6f2fe'
down_revision = 'e42cfe747172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('padi_data', sa.JSON(none_as_null=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_shop', schema=None) as batch_op:
        batch_op.drop_column('padi_data')

    # ### end Alembic commands ###
