"""add google_name for areaone

Revision ID: 2c66e1a24dd0
Revises: 2fbc56c38d88
Create Date: 2022-08-04 12:33:55.480815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c66e1a24dd0'
down_revision = '2fbc56c38d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_one', sa.Column('google_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area_one', 'google_name')
    # ### end Alembic commands ###
