"""change name from url to website

Revision ID: 2fbc56c38d88
Revises: 0c27a42b2939
Create Date: 2022-07-31 16:46:53.387732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbc56c38d88'
down_revision = '0c27a42b2939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dive_shop', 'url', new_column_name='website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dive_shop', 'website', new_column_name='url')
    # ### end Alembic commands ###
