"""Add google name to area2 to separate from display name

Revision ID: 32a2a71c845c
Revises: 12f20b2d5438
Create Date: 2021-08-12 08:13:02.990459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a2a71c845c'
down_revision = '12f20b2d5438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_two', sa.Column('google_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area_two', 'google_name')
    # ### end Alembic commands ###
