"""add stamp uri to dive shop

Revision ID: 457a89541c62
Revises: 68b56a7e8edb
Create Date: 2022-05-24 14:26:53.993448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457a89541c62'
down_revision = '68b56a7e8edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dive_shop', sa.Column('stamp_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dive_shop', 'stamp_uri')
    # ### end Alembic commands ###
