"""Separate hero img vs logo img for dive shops

Revision ID: 476c647dab9e
Revises: 6a0feecead24
Create Date: 2023-02-04 16:48:22.591137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476c647dab9e'
down_revision = '6a0feecead24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_shop', schema=None) as batch_op:
        batch_op.drop_column('hero_img')

    # ### end Alembic commands ###
