"""add max depth field to reviews

Revision ID: 48057053d1ac
Revises: 27b65909b8ae
Create Date: 2022-04-18 10:21:21.787501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48057053d1ac'
down_revision = '27b65909b8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('max_depth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'max_depth')
    # ### end Alembic commands ###
