"""Add caption field to images

Revision ID: 52e49bcb85c0
Revises: 075b85d528dc
Create Date: 2021-09-20 07:10:04.746834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e49bcb85c0'
down_revision = '075b85d528dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('caption', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'caption')
    # ### end Alembic commands ###
