"""Add fake user field

Revision ID: 57c7f43fcdf1
Revises: 4dc8f65f694c
Create Date: 2021-07-21 15:36:27.156978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c7f43fcdf1'
down_revision = '4dc8f65f694c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_fake', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_fake')
    # ### end Alembic commands ###
