"""Add shortname field to country and area_one

Revision ID: 5b88d4325fc4
Revises: 5e69095b6d83
Create Date: 2021-08-11 16:57:49.039549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b88d4325fc4'
down_revision = '5e69095b6d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_one', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('country', sa.Column('short_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'short_name')
    op.drop_column('area_one', 'short_name')
    # ### end Alembic commands ###
