"""Add more connections between spots and location tables

Revision ID: 5e69095b6d83
Revises: 13608966fe61
Create Date: 2021-08-11 14:37:31.311310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e69095b6d83'
down_revision = '13608966fe61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot', sa.Column('area_one_id', sa.Integer(), nullable=True))
    op.add_column('spot', sa.Column('area_two_id', sa.Integer(), nullable=True))
    op.add_column('spot', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_spot_country', 'spot', 'country', ['country_id'], ['id'])
    op.create_foreign_key('fk_spot_area_two', 'spot', 'area_two', ['area_two_id'], ['id'])
    op.create_foreign_key('fk_spot_area_one', 'spot', 'area_one', ['area_one_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_spot_country', 'spot', type_='foreignkey')
    op.drop_constraint('fk_spot_area_two', 'spot', type_='foreignkey')
    op.drop_constraint('fk_spot_area_one', 'spot', type_='foreignkey')
    op.drop_column('spot', 'country_id')
    op.drop_column('spot', 'area_two_id')
    op.drop_column('spot', 'area_one_id')
    # ### end Alembic commands ###
