"""Add is_verified spot

Revision ID: 61a2e82aa4f3
Revises: 57c7f43fcdf1
Create Date: 2021-07-26 13:06:14.538023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a2e82aa4f3'
down_revision = '57c7f43fcdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.execute("UPDATE spot SET is_verified = true")
    op.alter_column('spot', 'is_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot', 'is_verified')
    # ### end Alembic commands ###
