"""AddDivePartner

Revision ID: 63c0cabba431
Revises: af11b5deeae9
Create Date: 2022-05-19 14:27:37.640750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c0cabba431'
down_revision = 'af11b5deeae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dive_partner_ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locality_id', sa.Integer(), nullable=True),
    sa.Column('area_two_id', sa.Integer(), nullable=True),
    sa.Column('area_one_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['area_one_id'], ['area_one.id'], ),
    sa.ForeignKeyConstraint(['area_two_id'], ['area_two.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['locality_id'], ['locality.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dive_partner_ad')
    # ### end Alembic commands ###
