"""Created and updated columns

Revision ID: 64f402c1e617
Revises: 33ffc1e47e42
Create Date: 2023-02-02 13:59:12.821871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f402c1e617'
down_revision = '33ffc1e47e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated')

    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('updated')

    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
