"""AddDifficulty

Revision ID: 65edcc4c267c
Revises: 48057053d1ac
Create Date: 2022-04-25 13:33:07.027285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65edcc4c267c'
down_revision = '48057053d1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('difficulty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'difficulty')
    # ### end Alembic commands ###
