"""AddUserBio

Revision ID: 691a6ab0aca8
Revises: 63c0cabba431
Create Date: 2022-05-21 22:01:04.742464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691a6ab0aca8'
down_revision = '63c0cabba431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
