"""Add locality short_name

Revision ID: 6c9d0ba64a32
Revises: 52e49bcb85c0
Create Date: 2021-09-21 13:43:30.441326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9d0ba64a32'
down_revision = '52e49bcb85c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locality', sa.Column('short_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locality', 'short_name')
    # ### end Alembic commands ###
