"""empty message

Revision ID: 732790d814bc
Revises: 2f4db5864a2d
Create Date: 2022-06-02 11:42:01.642873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732790d814bc'
down_revision = '2f4db5864a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('user', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'longitude')
    op.drop_column('user', 'latitude')
    # ### end Alembic commands ###
