"""Add google_name column to locality

Revision ID: 7c7a70eb62f8
Revises: 6c9d0ba64a32
Create Date: 2021-09-29 13:24:13.178493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7a70eb62f8'
down_revision = '6c9d0ba64a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locality', sa.Column('google_name', sa.String()))
    op.alter_column('locality', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locality', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('locality', 'google_name')
    # ### end Alembic commands ###
