"""empty message

Revision ID: 7cfc8cd422a4
Revises: 00408ec985fc
Create Date: 2021-08-06 11:01:01.976143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfc8cd422a4'
down_revision = '00408ec985fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot', sa.Column('google_place_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot', 'google_place_id')
    # ### end Alembic commands ###
