"""Add has_pro to user model

Revision ID: a099cf06c2c4
Revises: 8225dd1a9a27
Create Date: 2022-08-10 15:47:39.893031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a099cf06c2c4'
down_revision = '8225dd1a9a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_pro', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_pro')
    # ### end Alembic commands ###
