"""Add non-nullable constraint to tag shortname

Revision ID: a24fafa4e467
Revises: 20e53de3f32e
Create Date: 2022-01-17 12:27:31.665562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24fafa4e467'
down_revision = '20e53de3f32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
