"""Add url column for locs

Revision ID: a3998bc31595
Revises: a24fafa4e467
Create Date: 2022-01-17 12:52:05.162721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3998bc31595'
down_revision = 'a24fafa4e467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_one', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'area_one', ['url'])
    op.add_column('area_two', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'area_two', ['url'])
    op.add_column('country', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'country', ['url'])
    op.add_column('locality', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'locality', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locality', 'url')
    op.drop_column('country', 'url')
    op.drop_column('area_two', 'url')
    op.drop_column('area_one', 'url')
    # ### end Alembic commands ###
