"""Add ratings and num reviews to dive shops

Revision ID: a5e75586a6e3
Revises: 476c647dab9e
Create Date: 2023-02-05 18:08:25.519224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e75586a6e3'
down_revision = '476c647dab9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('num_reviews', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_shop', schema=None) as batch_op:
        batch_op.drop_column('num_reviews')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
