"""Make locality names not nullable

Revision ID: be6780890e25
Revises: e523bfa64a19
Create Date: 2021-08-18 10:16:28.602101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6780890e25'
down_revision = 'e523bfa64a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('area_one', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('area_one', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('area_two', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('area_two', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('country', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('country', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('country', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('area_two', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('area_two', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('area_one', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('area_one', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
