"""Add ScheduledEmail table for Pro subscription automation

Revision ID: c41ee6a08991
Revises: 5274015c42ef
Create Date: 2025-07-07 22:02:38.269940

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c41ee6a08991"
down_revision = "5274015c42ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_email",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email_type", sa.String(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("template_id", sa.String(), nullable=False),
        sa.Column("dynamic_template_data", sa.JSON(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    op.drop_table("scheduled_email")
    # ### end Alembic commands ###
