"""ImageCreated

Revision ID: d1d65dddc251
Revises: 6dfdb43f973a
Create Date: 2022-05-06 11:13:12.023180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d65dddc251'
down_revision = '6dfdb43f973a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('created', sa.DateTime(), nullable=True))
    op.execute('UPDATE image SET created = NOW()')
    op.alter_column('image', 'created', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'created')
    # ### end Alembic commands ###
