"""Add wannadive table

Revision ID: d691bdf0b232
Revises: adef0bfad903
Create Date: 2022-01-06 21:35:14.173170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd691bdf0b232'
down_revision = 'adef0bfad903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wanna_dive_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wanna_dive_data')
    # ### end Alembic commands ###
