"""add name to dive shop

Revision ID: d8c26acf876a
Revises: 732790d814bc
Create Date: 2022-06-04 21:10:34.578294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c26acf876a'
down_revision = '732790d814bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dive_shop', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dive_shop', 'name')
    # ### end Alembic commands ###
