"""Ensure padi Ids are unique

Revision ID: da269d451515
Revises: ac53313fbb3c
Create Date: 2022-07-20 17:57:45.428446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da269d451515'
down_revision = 'ac53313fbb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('padi_store_id_unique', 'dive_shop', ['padi_store_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('padi_store_id_unique', 'dive_shop', type_='unique')
    # ### end Alembic commands ###
