"""empty message

Revision ID: dbbd634bd9cf
Revises: a099cf06c2c4
Create Date: 2022-08-23 14:34:48.144948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbd634bd9cf'
down_revision = 'a099cf06c2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'is_private')
    # ### end Alembic commands ###
