"""add additional dive shop column for padi import

Revision ID: e26e3086f57c
Revises: f69f31bbf7d2
Create Date: 2022-07-20 12:58:22.144880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26e3086f57c'
down_revision = 'f69f31bbf7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dive_shop', sa.Column('padi_store_id', sa.String(), nullable=True))
    op.add_column('dive_shop', sa.Column('country_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dive_shop', 'country_name')
    op.drop_column('dive_shop', 'padi_store_id')
    # ### end Alembic commands ###
