"""store google place ID

Revision ID: e42cfe747172
Revises: a5e75586a6e3
Create Date: 2023-02-05 18:51:03.558960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42cfe747172'
down_revision = 'a5e75586a6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_place_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_shop', schema=None) as batch_op:
        batch_op.drop_column('google_place_id')

    # ### end Alembic commands ###
