"""Add private key contraint to wannadive date

Revision ID: efd6bfcbe174
Revises: d691bdf0b232
Create Date: 2022-01-06 22:54:43.870957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd6bfcbe174'
down_revision = 'd691bdf0b232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wanna_dive_data', sa.Column('spot_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wanna_dive_data', 'spot', ['spot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wanna_dive_data', type_='foreignkey')
    op.drop_column('wanna_dive_data', 'spot_id')
    # ### end Alembic commands ###
