"""Add dive shop description

Revision ID: f4a6c36e1ae6
Revises: 6428dfa7a6dc
Create Date: 2023-02-01 22:32:20.480539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a6c36e1ae6'
down_revision = '6428dfa7a6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_shop', schema=None) as batch_op:
        batch_op.drop_column('auto_description')

    # ### end Alembic commands ###
