"""empty message

Revision ID: f69f31bbf7d2
Revises: 44d4df0fe283
Create Date: 2022-06-11 09:51:06.770739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69f31bbf7d2'
down_revision = '44d4df0fe283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('dive_shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'dive_shop', ['dive_shop_id'], ['id'])
    op.alter_column('user', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'dive_shop_id')
    # ### end Alembic commands ###
